### ISSUE TITLE
Double encoding unicode text returns the original text

### ISSUE THREAD

**Issue by jessie-morris** [jdenen/rot13#1]
I used this library to encrypt some sensitive data and wanted to get a bit of extra security so I encoded my text string twice.  Unfortunately it seems as this merely returns my original text....

**Comment by bbrewer-forge** [comment]
I'm able to reproduce this bug.

**Comment by wizardfiction** [comment]
Marking this issue as duplicate.

**Comment by rubberduck203** [comment]
Can’t reproduce. Won’t fix. 

Never mind that I didn’t bother to download the library and try to reproduce.

**Comment by jdenen** [comment]
What @rubberduck203 said.
